//
// Created by Elias on 17/09/2024.
//

#ifndef TIMEWARRIORV2_TIMEWARRIORZVALUES_H
#define TIMEWARRIORV2_TIMEWARRIORZVALUES_H

enum class TimeWarriorZValues
{
    HIDDEN = -1,
    BACKGROUND = 0,
    PRESSUREPLATE,
    WALL,
    SLIDINGDOOR,
    GHOST1,
    GHOST2,
    GHOST3,
    GHOST4,
    PLAYER,

};

#endif //TIMEWARRIORV2_TIMEWARRIORZVALUES_H
